### ISSUE TITLE
Dimension reduction option

### ISSUE THREAD

**Issue by tupui** [mbaudin47/othdrplot#13]
http://openturns.github.io/openturns/master/user_manual/stochastic_process.html#karhunen-loeve-decomposition

**Comment by mbaudin47** [comment]
Modify the class ProcessHighDensityRegionAlgorithm so that the constructor is:
```
ProcessHighDensityRegionAlgorithm (processSample, reducedSample, reducedDistribution)
```

**Comment by mbaudin47** [comment]
- check that dimension of reducedSample and reducedDistribution match
- check that size processSample and reducedSample match

**Comment by mbaudin47** [comment]
This ticket is linked to:

https://github.com/openturns/openturns/issues/1049

The new constructor might be:

ProcessHighDensityRegionAlgorithm (processSample, KLresult)

**Comment by mbaudin47** [comment]
The dimensionReductionSummary method should be removed.
