### ISSUE TITLE
The Readme.rst is broken

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/othdrplot#21]
The Readme.rst is broken : the layout in github is not nice anymore.

**Comment by tupui** [comment]
This is due to the inconsistency in the title formatting. Starting from `Algorithm`, the heading level is not correct. Also, this part is partially in french and the todo section could be removed in favour of issues here.

**Comment by tupui** [comment]
@mbaudin47 do I let you handle it, or?

**Comment by mbaudin47** [comment]
http://rst.ninjs.org
