### ISSUE TITLE
The logic behind HighDensityRegionAlgorithm.plotContour is weird.

### ISSUE THREAD

**Issue by mbaudin47** [mbaudin47/othdrplot#6]
The logic behind HighDensityRegionAlgorithm.plotContour is weird.

This is the current code: 
- plotContour(plotData=False, plotOutliers=False) : plots contours and outliers
- plotContour(plotData=False, plotOutliers=True) : plots contours and inliers
- plotContour(plotData=True, plotOutliers=True) : plots contours, outliers and inliers

The two functionnalities should be separated into three methods:
- drawContour() : plots only the contour
- drawInliers() : plots the inliers
- drawOutliers() : plots the outliers

**Comment by tupui** [comment]
OK to separate this method into three methods. @mbaudin47  Then what is the desired API for `ProcessHighDensityRegionAlgorithm`?

**Comment by tupui** [comment]
I have done a proposition in #9 .

**Comment by tupui** [comment]
Do pairplot in n-dimension using the 2D distribution using `self.distribution.getMarginal([i, j])`

**Comment by mbaudin47** [comment]
Pour créer un subplot contenant des graphiques OT, voir "Annexe : dessiner plusieurs distributions dans un même graphique" dans : 

https://github.com/mbaudin47/otsupgalilee-eleve/blob/master/1-Intro-OT/Distributions.ipynb
